# Generated by Django 4.0.5 on 2022-06-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_rename_brands_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
