# Generated by Django 4.0.5 on 2022-06-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='alert',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_date',
            field=models.DateTimeField(null=True),
        ),
    ]
