# Generated by Django 4.0.5 on 2022-06-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0003_alert_new_price_alert_new_price_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='promo_code',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
